### ISSUE TITLE
I got an errors when I was trying to do data preprocessing  

### ISSUE THREAD

**Issue by Blessing988** [mrdbourke/zero-to-mastery-ml#20]
```I was trying to follow your steps to convert the categorical features in the car_sales dataframe to numbers but got some errors```

```This is the thread: ```
```https://github.com/scikit-learn/scikit-learn/issues/17741```

**Comment by mrdbourke** [comment]
Hey @Blessing988 

Did you try and update scikit-learn to 0.23 (as mentioned in the thread you linked)?

You might want to run something like:

`conda uninstall scikit-learn`
`conda install scikit-learn=0.23`

**Comment by Blessing988** [comment]
Yeah I have resolved the issue. I had to update my anaconda and re-install jupyter and scikit-learn.
Thanks
