### ISSUE TITLE
Cannot participate in Discord

### ISSUE THREAD

**Issue by ilpbjs** [mrdbourke/zero-to-mastery-ml#89]
I got this error message: 

Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends. You can see the full list of reasons here: https://support.discord.com/hc/en-us/articles/360060145013

**Comment by kRiShNa-429407** [comment]
Have you joined the discord?

**Comment by ilpbjs** [comment]
I downloaded Discord and signed up, and I’m in the group, it seems. Is there a step I need to complete in order to participate?

**Comment by ilpbjs** [comment]
It resolved. Closing this now.

**Comment by ilpbjs** [comment]
Closed
